# Generated by Django 4.2.20 on 2025-05-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(
                default="uploads/default.jpg", upload_to="uploads/"
            ),
        ),
    ]
